"""Add missing tables

Revision ID: d44deb7473be
Revises: c3d4e5f6a7b8
Create Date: 2026-02-24 21:43:32.214596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44deb7473be'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=True),
    sa.Column('level_id', sa.UUID(), nullable=True),
    sa.Column('student_first_name', sa.String(), nullable=False),
    sa.Column('student_last_name', sa.String(), nullable=False),
    sa.Column('student_date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('student_gender', sa.String(), nullable=True),
    sa.Column('student_address', sa.String(), nullable=True),
    sa.Column('student_previous_school', sa.String(), nullable=True),
    sa.Column('parent_first_name', sa.String(), nullable=False),
    sa.Column('parent_last_name', sa.String(), nullable=False),
    sa.Column('parent_email', sa.String(), nullable=False),
    sa.Column('parent_phone', sa.String(), nullable=False),
    sa.Column('parent_address', sa.String(), nullable=True),
    sa.Column('parent_occupation', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'CONVERTED_TO_STUDENT', name='admissionstatus'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('converted_student_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['converted_student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_applications_tenant_id'), 'admission_applications', ['tenant_id'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_class_id'), 'schedule', ['class_id'], unique=False)
    op.create_index(op.f('ix_schedule_tenant_id'), 'schedule', ['tenant_id'], unique=False)
    # op.create_unique_constraint('uix_class_subject', 'class_subjects', ['class_id', 'subject_id'])
    # op.create_unique_constraint('uix_classroom_department', 'classroom_departments', ['class_id', 'department_id'])
    op.drop_column('grades', 'semester')
    op.drop_column('grades', 'academic_year')
    op.drop_column('grades', 'subject')
    op.drop_column('grades', 'exam_date')
    op.drop_column('grades', 'grade_type')
    op.drop_column('grades', 'trimester')
    op.add_column('parent_students', sa.Column('relation_type', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('uix_parent_student'), 'parent_students', type_='unique')
    op.drop_column('parent_students', 'relationship')
    # op.create_unique_constraint('uix_subject_department', 'subject_departments', ['subject_id', 'department_id'])
    # op.create_unique_constraint('uix_subject_level', 'subject_levels', ['subject_id', 'level_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_subject_level', 'subject_levels', type_='unique')
    op.drop_constraint('uix_subject_department', 'subject_departments', type_='unique')
    op.add_column('parent_students', sa.Column('relationship', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uix_parent_student'), 'parent_students', ['parent_id', 'student_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('parent_students', 'relation_type')
    op.add_column('grades', sa.Column('trimester', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('grade_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('grades', sa.Column('exam_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('academic_year', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uix_classroom_department', 'classroom_departments', type_='unique')
    op.drop_constraint('uix_class_subject', 'class_subjects', type_='unique')
    op.drop_index(op.f('ix_schedule_tenant_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_class_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_admission_applications_tenant_id'), table_name='admission_applications')
    op.drop_table('admission_applications')
    # ### end Alembic commands ###
