"""final_sync

Revision ID: 00c064158d74
Revises: add_perf_indexes_001
Create Date: 2026-03-10 22:40:59.481865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c064158d74'
down_revision = 'add_perf_indexes_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance', if_exists=True)
    op.drop_index(op.f('ix_attendance_tenant_date'), table_name='attendance', if_exists=True)
    op.drop_index(op.f('ix_audit_log_tenant_created'), table_name='audit_logs', if_exists=True)
    # op.create_unique_constraint('uix_class_subject', 'class_subjects', ['class_id', 'subject_id'])
    pass
    # op.create_unique_constraint('uix_classroom_department', 'classroom_departments', ['class_id', 'department_id'])
    pass
    op.drop_index(op.f('ix_students_tenant_status'), table_name='students', if_exists=True)
    # op.create_unique_constraint('uix_subject_department', 'subject_departments', ['subject_id', 'department_id'])
    pass
    # op.create_unique_constraint('uix_subject_level', 'subject_levels', ['subject_id', 'level_id'])
    pass
    op.drop_index(op.f('ix_tenants_is_active'), table_name='tenants', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tenants_is_active'), 'tenants', ['is_active'], unique=False)
    op.drop_constraint('uix_subject_level', 'subject_levels', type_='unique')
    op.drop_constraint('uix_subject_department', 'subject_departments', type_='unique')
    op.create_index(op.f('ix_students_tenant_status'), 'students', ['tenant_id', 'status'], unique=False)
    op.drop_constraint('uix_classroom_department', 'classroom_departments', type_='unique')
    op.drop_constraint('uix_class_subject', 'class_subjects', type_='unique')
    op.create_index(op.f('ix_audit_log_tenant_created'), 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_attendance_tenant_date'), 'attendance', ['tenant_id', 'date'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    # ### end Alembic commands ###
