"""Add user roles and security settings

Revision ID: 5a0a36c8b0ab
Revises: 38378961d475
Create Date: 2026-02-21 09:21:32.628225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a0a36c8b0ab'
down_revision = '38378961d475'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Radical cleanup of existing enum types to avoid DuplicateObject errors
    op.execute("DROP TYPE IF EXISTS studentstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS gender CASCADE")
    op.execute("DROP TYPE IF EXISTS invoicestatus CASCADE")
    op.execute("DROP TYPE IF EXISTS paymentmethod CASCADE")
    op.execute("DROP TYPE IF EXISTS paymentstatus CASCADE")

    # Create enum types manually
    op.execute("CREATE TYPE studentstatus AS ENUM ('ACTIVE', 'SUSPENDED', 'GRADUATED', 'DROPPED_OUT')")
    op.execute("CREATE TYPE gender AS ENUM ('MALE', 'FEMALE', 'OTHER')")
    op.execute("CREATE TYPE invoicestatus AS ENUM ('DRAFT', 'SENT', 'PAID', 'OVERDUE', 'CANCELLED')")
    op.execute("CREATE TYPE paymentmethod AS ENUM ('CASH', 'BANK_TRANSFER', 'MOBILE_MONEY', 'CARD')")
    op.execute("CREATE TYPE paymentstatus AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    
    op.create_table('tenant_security_settings',
    sa.Column('mfa_required', sa.Boolean(), nullable=True),
    sa.Column('password_expiry_days', sa.Integer(), nullable=True),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_security_settings_tenant_id'), 'tenant_security_settings', ['tenant_id'], unique=False)
    
    op.create_table('grades',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('grade_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('trimester', sa.Integer(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.create_index(op.f('ix_grades_tenant_id'), 'grades', ['tenant_id'], unique=False)
    
    op.create_table('invoices',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', postgresql.ENUM(name='invoicestatus', create_type=False), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_student_id'), 'invoices', ['student_id'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    
    op.create_table('rgpd_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rgpd_logs_tenant_id'), 'rgpd_logs', ['tenant_id'], unique=False)
    
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_tenant_id'), 'user_roles', ['tenant_id'], unique=False)
    
    op.create_table('payments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', postgresql.ENUM(name='paymentmethod', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM(name='paymentstatus', create_type=False), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    
    op.add_column('academic_years', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('academic_years', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_academic_years_tenant_id'), 'academic_years', ['tenant_id'], unique=False)
    
    op.alter_column('account_deletion_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('account_deletion_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False, server_default=sa.text('now()'))
    op.create_index(op.f('ix_account_deletion_requests_tenant_id'), 'account_deletion_requests', ['tenant_id'], unique=False)
    
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False, server_default=sa.text('now()'))
               
    op.add_column('students', sa.Column('registration_number', sa.String(length=50), nullable=False, server_default='TEMP'))
    op.add_column('students', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('level', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('class_name', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('academic_year', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('status', postgresql.ENUM(name='studentstatus', create_type=False), nullable=True, server_default='ACTIVE'))
    op.add_column('students', sa.Column('parent_name', sa.String(length=200), nullable=True))
    op.add_column('students', sa.Column('parent_phone', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('parent_email', sa.String(length=255), nullable=True))
    op.alter_column('students', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False, server_default='2000-01-01')
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM(name='gender', create_type=False),
               nullable=False,
               postgresql_using="gender::gender", server_default='MALE')
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('students', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False, server_default=sa.text('now()'))
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=False)
    op.create_index(op.f('ix_students_registration_number'), 'students', ['registration_number'], unique=True)
    op.create_index(op.f('ix_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    op.drop_column('students', 'matricule')
    op.drop_column('students', 'user_id')
    op.drop_column('students', 'is_archived')
    
    op.add_column('tenants', sa.Column('country', sa.String(length=2), nullable=False, server_default='GN'))
    op.add_column('tenants', sa.Column('currency', sa.String(length=3), nullable=True, server_default='GNF'))
    op.add_column('tenants', sa.Column('timezone', sa.String(length=50), nullable=True, server_default='Africa/Conakry'))
    op.alter_column('tenants', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False, server_default=sa.text('now()'))
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'address')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'logo_url')
    op.drop_column('tenants', 'website')
    
    op.add_column('users', sa.Column('keycloak_id', sa.String(length=255), nullable=False, server_default='TEMP'))
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False, server_default='TEMP'))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_keycloak_id'), 'users', ['keycloak_id'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_keycloak_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'tenant_id')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'username')
    op.drop_column('users', 'keycloak_id')
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS studentstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS gender CASCADE")
    op.execute("DROP TYPE IF EXISTS invoicestatus CASCADE")
    op.execute("DROP TYPE IF EXISTS paymentmethod CASCADE")
    op.execute("DROP TYPE IF EXISTS paymentstatus CASCADE")
    # ### end Alembic commands ###
