"""add_missing_tenant_models_and_fields

Revision ID: 5c72a2069458
Revises: 5a0a36c8b0ab
Create Date: 2026-02-21 15:13:58.156284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c72a2069458'
down_revision = '5a0a36c8b0ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campuses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campuses_tenant_id'), 'campuses', ['tenant_id'], unique=False)
    op.create_table('levels',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levels_tenant_id'), 'levels', ['tenant_id'], unique=False)
    op.create_table('subjects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_tenant_id'), 'subjects', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('academic_years_tenant_id_fkey'), 'academic_years', type_='foreignkey')
    op.drop_constraint(op.f('account_deletion_requests_tenant_id_fkey'), 'account_deletion_requests', type_='foreignkey')
    op.drop_constraint(op.f('students_tenant_id_fkey'), 'students', type_='foreignkey')
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('website', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenants', 'website')
    op.drop_column('tenants', 'address')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'email')
    op.create_foreign_key(op.f('students_tenant_id_fkey'), 'students', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('account_deletion_requests_tenant_id_fkey'), 'account_deletion_requests', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('academic_years_tenant_id_fkey'), 'academic_years', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_subjects_tenant_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_levels_tenant_id'), table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_campuses_tenant_id'), table_name='campuses')
    op.drop_table('campuses')
    # ### end Alembic commands ###
